baseURL = 'https://blitzkrieg-patch.github.io/'
languageCode = 'en-us'
title = "Decompiling blitzkrieg’s homepage… oh wait, "
theme = 'hugo-theme-reimu'

[markup.highlight]
guessSyntax = true
noClasses = false

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
[params]
  math = true